Algoritmo "EX03_2"

Var
// Seção de Declarações das variáveis 
   n1, n2, total : inteiro

Inicio

      //entrada de dados
      escreva("Digite um numero : ")
      leia(n1)
      
      escreva("Digite um numero: ")
      leia(n2)
      
      //processamento
      total <- n1 + n2
      escreval("Soma = ", total)
      
      total <- n1 - n2
      escreval("Subtracao = ",total)
      
      total <- n1 * n2
      escreval("Multiplicacao = ", total)
      
Fimalgoritmo