algoritmo "Ex_13"
var
     A, B, C : real
     S : real
inicio

      //entrada de dados
      escreva("Valor A: ")
      leia(A)
      
      escreva("Valor B: ")
      leia(B)
      
      escreva("Valor C: ")
      leia(C)
      
      //processamento - primeira solução
      
      //S <- A^2 + B^2 + C^2
      
      //processamento - segunda solução
      
      S <- exp(A,2) + exp(B,2) + exp(C,2)
      
      //saída
      escreva("Soma dos quadrados = ", S)

fimalgoritmo