Algoritmo "idade"

Var

      idade : inteiro

Inicio

       escreval("Qual a sua idade?")
       leia(idade)
       
       //composta
       
       se( idade >= 67 ) então
       
          escreval("Parabéns, você já pode ser vacinado(a)")

       senão
       
            escreval("Aguarde a sua vez para ser vacinado(a)")

       fimse
       
       
       
       escreval("Obrigada por acessar o sistema")

Fimalgoritmo