Algoritmo "SOMA2NUMEROS"

Var
// Seção de Declarações das variáveis 

   A : inteiro
   B, C : inteiro

Inicio

      //fase entrada de dados

     //comando de saída
     escreva("Digite um numero: ")
     
     //comando de entrada
     leia(A)
     
     escreva("Digite outro numero: ")
     leia(B)
     
     //processamento
      C <- A + B
      
      // fase saída de dados
      escreva(C)

Fimalgoritmo